# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6adcfe68a1e9f858c9135e7561deaf095ef0c29bc36a887dbabe972de86b7292bab81190f3cdd17c96a85601dcd8a72b168a8943fb770ceada84816ea7bd578f

test:
  secret_key_base: 05085306850e9dd27307775ab94068c815975707b22529b4aab4304e8d6555d1d1ef741c6dadd32b03591c0ba57f5a22d5824b5b5f44f50f068f4aa208596f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
